### ISSUE TITLE
Wrong formatting of authors list 

### ISSUE THREAD

**Issue by Nelson-Gon** [Nelson-Gon/pycite#1]
**Describe the bug**

Authors list is not of the desired format.

**To Reproduce**

Run `cite` for a text file. 

**Expected behavior**

Expected to have authors listed as per the Harvard referencing style. 

**Unexpected behavior**

Authors list was of the unexpected format. Specifically, I got misplaced `&` and `and`. 

**System Details**

Latest version: https://github.com/Nelson-Gon/pycite/tree/c83db0df6d0d3f176189f0538a4ef04fa0e3dca1

**Comment by leevic31** [comment]
Hello, I am new to contributing to open source projects. I would like to work on this issue.

**Comment by Nelson-Gon** [comment]
Hi, thank you for your interest in this project.  Please take a look at the [contributing guide](https://github.com/Nelson-Gon/pycite/blob/main/.github/CONTRIBUTING.md) which may be useful.

For this issue, the current problem is  that some names are not abbreviated. For example in https://github.com/Nelson-Gon/pycite/blob/467bead577a47d931220fef7d53db4117a385cd3/tests.py, we should have the name "Wilson" abbreviated to W but that is not the case. If we have the name "Nelson Gon Developer", we should change this to Developer NG per Harvard style. 

Hopefully this makes sense but please do let me know if you have further questions.

Keep Building,

NelsonGon
