### ISSUE TITLE
Error message when running program based on README.rst instructions

### ISSUE THREAD

**Issue by HudsonLanier** [Nelson-Gon/pycite#11]
**Describe the bug**

When running the program per the directions in README.rst, the program errors out

**To Reproduce**

Go to line 162 of README.rst and do as follows:
```
from pycite.pycite import PyCite
my_citations = PyCite(input_file="testfiles/testlinks.txt", output_file="testfiles/citations.txt")
my_citations.cite()
```

`my_citations.cite()` will run correctly for a short time and then give the following error message when trying to cite this (https://www.sciencedirect.com/science/article/pii/S0301051117302314) article:

>(Traceback (most recent call last):
File "", line 1, in
File "/home/hudsonlanier/.virtualenvs/pycite/lib/python3.9/site-packages/pycite/pycite.py", line 132, in cite
title = bs4_link.find_all("h1", {"class": "content-title"})[0].text
IndexError: list index out of range)

**Expected behavior**
The expectation is that this will either correctly cite the article or at least not error out the program as a result of not being able to cite the article.

**Unexpected behavior**

>Traceback (most recent call last):
File "", line 1, in
File "/home/hudsonlanier/.virtualenvs/pycite/lib/python3.9/site-packages/pycite/pycite.py", line 132, in cite
title = bs4_link.find_all("h1", {"class": "content-title"})[0].text
IndexError: list index out of range

**System Details**

----

**Comment by Nelson-Gon** [comment]
I have taken a look and it seems this calls `ncbi` methods https://github.com/Nelson-Gon/pycite/blob/1fae8bad0a1e6fedf20f8d0441f3f6f0cd0d5091/pycite/ncbi.py#L11 instead of the science direct method https://github.com/Nelson-Gon/pycite/blob/5dbe9743baad34b783820631c98a29ad2632f3fb/pycite/sciencedirect.py#L13

I am not sure why this is the case as I cannot reproduce unfortunately.

**Comment by HudsonLanier** [comment]
Hey Nelson-Gon,

Sorry for the slow reply. Just got back from a trip to West Virginia. Now, when I installed the program, I used the "Clone in Pycharm" button. Is it possible that this has something to do with this issue?

**Comment by Nelson-Gon** [comment]
Hi @HudsonLanier,

Thank you for the update. I think using `clone` would have no issue. That said, could you please let me know what the following output at the terminal?

```
 git log -1 --pretty=format:"%h"
```

And 

```
git reset --hard origin/main && git clean -fd && git log -1 --pretty=format:"%h"
```

Thanks,

Nelson

**Comment by Nelson-Gon** [comment]
Closed due to no response.
