### ISSUE TITLE
Script Generator Fails on Linux Systems 

### ISSUE THREAD

**Issue by Nelson-Gon** [Nelson-Gon/pycite#13]
**Describe the bug**

When running `bash scripts/mkdocs.sh`, I received errors. 

**To Reproduce**

On a Linux system while in the directory's root, run `bash scripts/mkdocs.sh`. 

**Expected behavior**

I expected to have documentation build flawlessly or at least attempt to build. 

**Unexpected behavior**
I received the following errors:

>/usr/bin/python3: No module named m2r
mv: cannot stat '.github/CONTRIBUTING.rst': No such file or directory
mv: cannot stat 'README.rst': No such file or directory
mv: cannot stat 'changelog.rst': No such file or directory
Building docs for pycite
scripts/mkdocs.sh: line 23: ./make.bat: Permission denied

**System Details**

OS: Linux 5.8.0-55-generic #62~20.04.1-Ubuntu 

Package hash: https://github.com/Nelson-Gon/pycite/tree/914367ac61bd11d2e7ed4bb84e716cc45392ea38

**Comment by TheAnshul756** [comment]
No module names m2r is found which could be because you have not installed requirements.txt.
run command `pip install -r requirements.txt`

**Comment by Nelson-Gon** [comment]
Hi @TheAnshul756,
Thank you. For the no module error, it also is due to using a non-system pip which means modules are not on path. This can be solved by adding wherever pip has installed packages to to $PATH.

That said, I think there should be a way to make it easier to just run the script out-of-the-box.

**Comment by TheAnshul756** [comment]
Script uses m2r module and it would not be possible to run the script without installing m2r module beforehand. One solution to this could be to check if m2r is already installed and if not install m2r.
If you want, I can add this check to the script.

**Comment by Nelson-Gon** [comment]
Thanks @TheAnshul756, here are a few other ideas I've been thinking of:
* Check `which python` and use that instead of a hardcoded `python`call
* If `Linux`, use `make` not `make.bat`
* Not sure how this can be done but perhaps have a Linux specific Makefile?

If this sounds good, please submit a PR and I'll review. 

Thanks,

Nelson

**Comment by TheAnshul756** [comment]
Hello @Nelson-Gon 
Created a pull request #14 , please review it.

**Comment by Nelson-Gon** [comment]
Closed in #63bb5a6c5b95ef8a8f24b08f1353661da4153e6b Thanks!
