### ISSUE TITLE
Sort generated citations alphabetically 

### ISSUE THREAD

**Issue by Nelson-Gon** [Nelson-Gon/pycite#19]
**Description**

As per Harvard citation standards, the citation list should be ordered alphabetically. 

**Similar Features**

Related to `pycite.cite()` and/or the individual `*_final_citation`

**Feature Details**

Sufficiently described. 

**Proposed Implementation**

A simple name based sort of the generated citation list?

**Comment by Swanand01** [comment]
Hello @Nelson-Gon, I'd like to take this up please. It'd be great if you could guide me on where the sort is to be implemented. Thanks!

**Comment by Nelson-Gon** [comment]
Hi, @Swanand01. Thank you for your interest.  For this issue, we need to sort the generated citations file before saving it. Essentially, as we write to the file, somewhere between lines 73 and 95 https://github.com/Nelson-Gon/pycite/blob/2642a304c6137582f349296166f6fcf3cf8b3576/pycite/pycite.py#L73-#L95 we should perform the sort.

A possible way to do this is to:

* Copy the file somewhere before writing it, sort the lines with `sorted(file.readlines())` and then rewrite it. This may take more time and computational resources.
* Alternatively, we could sort individually via the individual methods e.g. in `pubmed.py`. This method seems less ideal as one would need to rewrite everything. We currently do not write to a file in the individual modules.

This is my current idea, let me know what you think and/or if I should clarify further.

Thanks,

Nelson

**Comment by Swanand01** [comment]
Hi, this is what I understand:
The output file is being written by the inside the switch_method, on line 32
`output_file.write(f"{actual_method}\n")`
 This switch_method() is being called from the cite() method at line 92:
`switch_method(line, in_file, out_file, final_citations, bs4_link, show_doi=self.show_doi)`.

Please correct me if I'm wrong.

**Comment by Nelson-Gon** [comment]
Yes, that's correct @Swanand01
